image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
    - python -m flake8

black:
  stage: Static Analysis
  script:
    - python -m black --check .

mypy:
  stage: Static Analysis
  script:
    - python -m mypy .

test:
  stage: Test
  script:
  - python -m pytest
